networks:
  devNetwork:
    driver: ${NETWORKS_DRIVER}

services:
  mysql:
    image: mysql:8.0
    privileged: true
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${MYSQL_USERNAME}                  # MySQL username
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}              # MySQL user password
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}    # MySQL root user password
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - ${MySQL_PATH}:/var/lib/mysql 
    ports:
      - "${MYSQL_PORT}:3306"                          # mapping 3306 port
    networks:
      - devNetwork
    deploy:
      resources:
        limits:
          memory: ${LIMIT_MEMORY_MYSQL}
    restart: always

  redis:
    image: redis:5.0
    environment:
      - TZ=${TZ}
    privileged: true
    volumes:
      - ${REDIS_PATH}:/data
    ports:
      - "${REDIS_PORT}:6379"                          # mapping 6379 port
    networks:
      - devNetwork
    deploy:
      resources:
        limits:
          memory: ${LIMIT_MEMORY_REDIS}
    restart: always
