networks:
  innerNetwork:
    driver: ${NETWORKS_DRIVER}

services:
  database:
    image: mysql:8.0
    privileged: true
    environment:
      - TZ=${TZ}
      - MYSQL_USER=${DATABASE_USERNAME}                  # MySQL username
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}              # MySQL user password
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}    # MySQL root user password
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - ${DATABASE_PATH}:/var/lib/mysql
    ports:
      - "${DATABASE_PORT}:3306"                          # mapping 3306 port
    networks:
      - innerNetwork
    deploy:
      resources:
        limits:
          memory: ${LIMIT_MEMORY_DATABASE}
    restart: always

  redis:
    image: redis:5.0
    environment:
      - TZ=${TZ}
    privileged: true
    volumes:
      - ${REDIS_PATH}:/data
    ports:
      - "${REDIS_PORT}:6379"                          # mapping 6379 port
    networks:
      - innerNetwork
    deploy:
      resources:
        limits:
          memory: ${LIMIT_MEMORY_REDIS}
    restart: always
